New_Test/accounts/urls.py
from django.urls import path
from . import views
from .views import view_profile, edit_profile

app_name = "accounts"

urlpatterns = [
    path("<int:pk>/follow/", views.follow, name="follow"),
    path("signup/", views.signup, name="signup"),
    path("update/", views.update, name="update"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path('view_profile/', view_profile, name='view_profile'),
    path('edit_profile/', edit_profile, name='edit_profile'),
]

New_Test/plant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls", namespace='accounts')),
    path('', TemplateView.as_view(template_name="main/main.html"), name="main"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

New_Test/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User

class CustomUser(AbstractUser):
    followings = models.ManyToManyField(
        "self", symmetrical=False, related_name="followers_set"
    )
    
    groups = models.ManyToManyField(
        "auth.Group", 
        verbose_name=("groups"),
        blank=True,
        help_text=("The groups this user belongs to."),
        related_name="customuser_groups"  # Change this related_name
    )
    user_permissions = models.ManyToManyField(
        "auth.Permission",
        verbose_name=("user permissions"),
        blank=True,
        help_text=("Specific permissions for this user."),
        related_name="customuser_permissions"  # Change this related_name
    )
    
    def __str__(self):
        return self.email

    @property
    def full_name(self):
        return f"{self.last_name} {self.first_name}"

    
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True)
    # 프로필 이미지가 비어있는 경우 기본 이미지 사용
    profile_picture = models.ImageField(
        upload_to='profile_pics/',
        blank=True,
        null=True,
        default='path/to/default/image.jpg'
    )
    
    def __str__(self):
        return self.user.username

New_Test/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser
from .models import UserProfile
class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ("username", "email")


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ("username", "email")


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['bio', 'profile_picture']
        
    def clean_profile_picture(self):
        profile_picture = self.cleaned_data.get('profile_picture')
        if not profile_picture:
            # 기본 이미지 경로로 설정
            profile_picture = 'path/to/default/image.jpg'
        return profile_picture

New_Test/accounts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth import get_user_model, login as auth_login, logout as auth_logout
from .forms import CustomUserCreationForm, CustomUserChangeForm
from .models import UserProfile
from .forms import UserProfileForm
from django.contrib.auth.forms import AuthenticationForm

def detail(request, pk):
    user = get_object_or_404(get_user_model(), pk=pk)
    context = {"user": user}
    return render(request, "accounts/detail.html", context)

@login_required
def follow(request, pk):
    user = get_user_model().objects.get(pk=pk)
    if request.user == user:
        messages.warning(request, "스스로 팔로우 할 수 없습니다.")
        return redirect("accounts:detail", pk)
    if request.user in user.followers.all():
        user.followers.remove(request.user)
    else:
        user.followers.add(request.user)
    return redirect("accounts:detail", pk)

def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.backend = 'django.contrib.auth.backends.ModelBackend'  # 백엔드 지정
            user.save()
            auth_login(request, user)
            return redirect("main")
    else:
        form = CustomUserCreationForm()
    context = {"form": form}
    return render(request, "accounts/signup.html", context)

def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect("main")
    else:
        form = AuthenticationForm()
    context = {"form": form}
    return render(request, "accounts/login.html", context)

def logout_view(request):
    auth_logout(request)
    messages.warning(request, "로그아웃 성공!")
    return redirect("main")

@login_required
def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("accounts:detail", request.user.pk)
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {"form": form}
    return render(request, "accounts/update.html", context)

# profile
@login_required
def view_profile(request):
    try:
        user_profile = UserProfile.objects.get(user=request.user)
    except UserProfile.DoesNotExist:
        user_profile = UserProfile.objects.create(user=request.user)
    return render(request, 'accounts/view_profile.html', {'user_profile': user_profile})

@login_required
def edit_profile(request):
    user_profile = UserProfile.objects.get(user=request.user)

    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=user_profile)
        if form.is_valid():
            form.save()
            return redirect('accounts:view_profile')
    else:
        form = UserProfileForm(instance=user_profile)

    return render(request, 'accounts/edit_profile.html', {'form': form})

New_Test/accounts/templates/accounts/change.html
{% extends 'base.html' %} {% block content %}
<h1>비밀번호 변경</h1>
<form action="{% url 'accounts:change' %}" method="POST">
  {% csrf_token %} {% bootstrap_form form %}
  <button type="submit">비밀번호 수정완료</button>
</form>
{% endblock %}

New_Test/accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %} {% block content %}
<div class="edit_profile">
  <div class="edit_content">
    <p class="edit_text">Edit Profile</p>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <!-- Existing form fields -->
    {{ form.as_p }}

    <button class="save_btn" type="submit">
      Save Changes</a>
    </button>
  </form>
  </div>
  
</div>
{% endblock %}

New_Test/accounts/templates/accounts/login.html
{% extends 'base.html' %} {% block content %}
<div class="login">
  <div class="login_content">
    <div class="login_text">
      <p class="login_p">Login</p>
    </div>
    <div class="login_form">
      <form
        method="post"
        action="{% url 'accounts:login' %}"
        class="login-form"
        id="loginForm"
      >
        {% csrf_token %}

        <div class="form-field">
          <label for="{{ form.username.id_for_label }}" class="form-label"
            >Username:</label
          >
          {{ form.username }}
        </div>

        <div class="form-field">
          <label for="{{ form.password.id_for_label }}" class="form-label"
            >Password:</label
          >
          {{ form.password }}
        </div>

        <button class="login_btn" type="button" onclick="submitForm()">
          Start Plant
        </button>
      </form>
    </div>
  </div>
</div>

{% endblock %}

New_Test/accounts/templates/accounts/signup.html
{% extends 'base.html' %} {% block content %}
<div class="signup">
  <div class="signup_content">
    <div class="signup_text">
      <p class="loginup_p">Sign Up</p>
      <div class="signup_form">
        <form method="post" action="{% url 'accounts:signup' %}">
          {% csrf_token %}

          <div class="form-field">
            <label for="{{ form.username.id_for_label }}">Username:</label>
            {{ form.username }}
          </div>

          <div class="form-field">
            <label for="{{ form.email.id_for_label }}">Email:</label>
            {{ form.email }}
          </div>

          <div class="form-field">
            <label for="{{ form.password1.id_for_label }}">Password:</label>
            {{ form.password1 }}
          </div>

          <div class="form-field">
            <label for="{{ form.password2.id_for_label }}"
              >Confirm Password:</label
            >
            {{ form.password2 }}
          </div>

          <button class="signup_btn" type="submit">Join</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

New_Test/accounts/templates/accounts/update.html
{% extends 'base.html' %} {% block content %}
<div class="update">
  <div class="update_content">
    <div class="update_text">
      <p class="update_p">프로필 업데이트</p>
    </div>
  </div>
  <div class="update_form">
    <form action="" method="POST">
      {% csrf_token %}
      <div>
        <a href="" aria-current="page">비밀번호 변경</a>
        <a href="" class="btn btn-secondary">회원탈퇴</a>
      </div>
      <button class="update_btn" type="submit">update</button>
    </form>
  </div>
</div>

{% endblock %}

New_Test/accounts/templates/accounts/view_profile.html
{% extends 'base.html' %} {% block content %} {% if user.is_authenticated %}
<div class="user_profile">
  <div class="user_info">
    <!--user_img-->
    {% if user.userprofile.profile_picture %}
    <img
      class="user_profile_img"
      src="{{ user.userprofile.profile_picture.url }}"
      alt="Profile Picture"
    />

    {% else %}
    <p>No profile picture available</p>
    {% endif %}
    <p class="user_name">{{ user.username }}'s Profile</p>
    <span class="user_bio">🌱 {{ user.userprofile.bio }}</span>
    <div class="edit_btn">
      <a href="{% url 'accounts:edit_profile' %}">프로필 수정하기</a>
    </div>
  </div>
</div>
{% endif %} {% endblock %}

New_Test/pages/templates/pages/home.html
{% load static %}
{% extends 'base.html' %}
{% block content %}
<!-- hello banner -->
<div class="hello_banner">
  <p class="hello_1">안녕하세요 :)</p>
  <p class="hello_2">PLANT를 소개합니다!</p>
</div>

<!-- banner card -->
<div class="banner_card">
  <div class="user_plant">
      <div class="user_plant_img">
        <img src="{% static 'images/images/olive.png' %}" alt="">
        <img src="{% static 'images/images/mons.png' %}" alt="">
        <img src="{% static 'images/images/yellow.png' %}" alt="">
      </div>
      <div class="user_card">
          <div class="user_content"></div>
          <div class="user_content"></div>
          <div class="user_content"></div>
      </div>
  </div>
</div>

<!-- together section -->
<div class="video">
  <img class="plant_video" src="{% static 'images/images/PLANT.gif' %}" alt="">
</div>
<div class="video_text">
  <div class="video_content_1">
    <p>누구나 식물과</p>
    <p>함께,</p>
  </div>
  <div class="video_content_2">
    <p>PLANT에서는 식물을 통해 그들만의 공간과 시간,</p>
    <p>그리고 마음을 채울 수 있다고 생각합니다.</p>
    <p>진정한 ‘나’를 위해 더 나은 라이프스타일을 고민하는 사람들이 있습니다.</p>
    <p>식물은 우리가 머무는 장소와 행동을 더욱 의미 있게 만들어줄 뿐만 아니라 우리의</p>
    <p>지친 마음과 생각을 치유하고 위로해주는 살아있는 오브제입니다.</p>
  </div>
</div

New_Test/plant/templates/main/main.html
{% extends 'base.html' %}{% load static %} {% block content %}
<!-- hello banner -->
<div class="hello_banner">
    <p class="hello_1">안녕하세요 :)</p> </br>
    <p class="hello_2">PLANT를 소개합니다!</p>
</div>


<!--banner card-->
<div class="banner_card">
<div class="user_plant">
    <div class="user_plant_img">
    <img src="{% static 'images/images/olive.png' %}" alt="">
    <img src="{% static 'images/images/mons.png' %}" alt="">
    <img src="{% static 'images/images/yellow.png' %}" alt="">
    </div>
    <div class="user_card">
        <div class="user_content">
            <div class="user_name">
                <p class="name">@loveplant 님의 반려식물</p>
            </div>
        </div>
        <div class="user_content">
            <div class="user_name">
                <p class="name">@loveplant 님의 반려식물</p>
            </div>
        </div>
        <div class="user_content">
            <div class="user_name">
                <p class="name">@loveplant 님의 반려식물</p>
            </div>
        </div>
    </div>
</div>
</div>

<!-- together section -->
<div class="video">
<img class="plant_video" src="{% static 'images/images/PLANT.gif' %}"></img>
</div>
<div class="video_text">
<div class="video_content_1">
    <p>누구나 식물과</p>
    <p>함께,</p>
</div>
<div class="video_content_2">
    <p> PLANT에서는 식물을 통해 그들만의 공간과 시간,</p>
    <p>그리고 마음을 채울 수 있다고 생각합니다.</p>
    <p>진정한 ‘나’를 위해 더 나은 라이프스타일을 고민하는 사람들이 있습니다.</p>
    <p>식물은 우리가 머무는 장소와 행동을 더욱 의미 있게 만들어줄 뿐만 아니라 우리의</p>
    <p>지친 마음과 생각을 치유하고 위로해주는 살아있는 오브제입니다.</p>
</div>
</div>
</div>

<!-- life section-->
<div class="life_title">
    <div class="title">
        <p>식물과 가까울수록</p>
        <p>건강한 삶의 변화</p>
    </div>
</div>
<div class="content_title">
    <p>건강</p>
    <p>행복</p>
    <p>즐거움</p>
</div>
<div class="content_img">
    <div class="img">
        <img src="{% static 'images/images/person_1.png' %}" alt="">
    </div>
    <div class="img">
        <img src="{% static 'images/images/person_2.png' %}" alt="">
    </div>
    <div class="img">
        <img src="{% static 'images/images/person_3.png' %}" alt="">
    </div>
</div>

<!-- ad section -->
<div class="ad_content">
<div class="ad_card_1">
    <p class="title_1">올바르게 식물 키우는 방법</p>
    <p class="title_2">반려식물 키우기</p>
    <p class="content">PLANT에서 식물 키우는 노하우에 대해 공유할 수 있어요.</p>
</div>
<div class="ad_card_1">
    <p class="title_1">가드너 식물 지킴이</p>
    <p class="title_2">안심하고 구입하기</p>
    <p class="content">PLANT에서 실물을 잘 키워나가는 경험에 집중할 수 있어요. </p>
</div>
<div class="ad_persion">
    <img src="{% static 'images/images/006.png' %}" alt="">
</div>
</div>
{% endblock %}

New_Test/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="author" content="Sukyung" />
    <!-- CSS Link -->
    <!-- accounts -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/login.css'%}" />
    <link rel="stylesheet" href="{% static 'css/signup.css'%}" />
    <link rel="stylesheet" href="{% static 'css/view_profile.css' %}" />
    <link rel="stylesheet" href="{% static 'css/edit_profile.css' %}" />
     <!-- articles -->
    <link rel="stylesheet" href="{% static 'css/articles_index.css' %}" />
    <link rel="stylesheet" href="{% static 'css/articles_forms.css' %}" />

    <!-- Google Icon -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
   
    <title>🪴Plant</title>

  </head>
  <body>
    <!-- Header -->
    <header id="mainHeader">
      <div class="menu_section">
        <div class="logo"><a href={% url 'main' %}>PLANT</a></div>
        <div class="menu">
          <p class="menu_list">반려식물 찾기</p>
          <p class="menu_list">
            전국식물자랑
          </p>
          <p class="menu_list">스토어</p>
        </div>

      </div>

      <!-- Nav -->
      <div class="nav">
        {% if user.is_authenticated %}
        <p class="welcome_msg">Welcome! {{ user.username }}!</p>
        <p><a href="{% url 'accounts:logout' %}">로그아웃</a></p>
        <p class="page1"><a href="{% url 'accounts:view_profile' %}">마이페이지</a></p>
        {% else %}
        <p></p>
        <p><a href="{% url 'accounts:login' %}">로그인</a></p>
        <p class="page2"><a href="{% url 'accounts:signup' %}">회원가입</a></p>
        {% endif %}
      </div>
    </header>

    <div class="block_content">
      
    {% block content %}

    {% endblock content %} 

    </div>
    
    <!-- footer -->
    <div class="bottom">
      <div class="footer_contact">
        <p>Contact</p>
        <div class="footer_text">
          <p>email : plant@email.com</p>
          <p>tell : 070-0000-0000 (11:00 am - 18:00 / 토,일,공휴일 휴무)</p>
          <p>@2024. PLANT corp. all rights reserevd. Django FullStack.</p>
        </div>
      </div>
    </div>


  </body>
  <!-- JavaScript only -->
  <script>
    window.addEventListener('scroll', function() {
      var header = document.getElementById('mainHeader');
      if (window.scrollY > 100) { 
        header.style.background = 'rgba(255, 255, 255, 1)'; 
      } else {
        header.style.background = 'rgba(255, 255, 255, 0.8)'; 
      }
    });
  </script>
</html>